### ISSUE TITLE
pixel gap on ios

### ISSUE THREAD

**Issue by joe06102** [SrBrahma/react-native-shadow-2#28]
When used on my own project on ios（plain react native project）, there are obvious gaps between corners & borders. But in expo demo, it works fine.

And the shadow works fine on android. I found some docs on the documentation about the gap but can not really understand it.

Appreciated if any one can help!

![shadow](https://user-images.githubusercontent.com/9021911/136652765-91ea73dd-6ed4-448f-b2db-017bf0190d49.jpg)
reproducable code:

```jsx
  <Shadow
    distance={15}
    startColor={'#000000ff'}
    finalColor={'#00000000'}
    offset={[10, 0]}
    radius={10}
    size={[100, 100]}
  >
    <View
      style={[
        {
          width: 100,
          height: 100,
          borderRadius: 10,
          backgroundColor: '#fff',
        },
      ]}
    ></View>
  </Shadow>
```

**Comment by joe06102** [comment]
https://snack.expo.dev/@joe06102/6c4fc6

I can not reproduce the problem on the expo. Do you have any idea how it happens?

**Comment by joe06102** [comment]
Thx, SrBrahma.

The output with size={[100,100]}(render only triggered once):

```json
{
  "scale": 2,
  "width": 100,
  "height": 100,
  "distance": 15,
  "radii": {
    "topLeft": 10,
    "topRight": 10,
    "bottomLeft": 10,
    "bottomRight": 10
  },
  "cornerShadowRadius": {
    "topLeftShadow": 25,
    "topRightShadow": 25,
    "bottomLeftShadow": 25,
    "bottomRightShadow": 25
  }
}
```

And the output without size props(render triggered twice):

```json
//the first
{
  "scale": 2,
  "width": "100%",
  "height": "100%",
  "distance": 15,
  "radii": {
    "topLeft": 10,
    "topRight": 10,
    "bottomLeft": 10,
    "bottomRight": 10
  },
  "cornerShadowRadius": {
    "topLeftShadow": 25,
    "topRightShadow": 25,
    "bottomLeftShadow": 25,
    "bottomRightShadow": 25
  }
}

// the second
{
  "scale": 2,
  "width": 100,
  "height": 100,
  "distance": 15,
  "radii": {
    "topLeft": 10,
    "topRight": 10,
    "bottomLeft": 10,
    "bottomRight": 10
  },
  "cornerShadowRadius": {
    "topLeftShadow": 25,
    "topRightShadow": 25,
    "bottomLeftShadow": 25,
    "bottomRightShadow": 25
  }
}
```

Unfortunately, the problems still happen in both case.

**Comment by SrBrahma** [comment]
I appreciate. Is there any gap when using radius={0}?

**Comment by joe06102** [comment]
with shadow' s radius = 0 & children's borderRadius = 0
![9a8d6f9176fd52b4e603d8a74d38894](https://user-images.githubusercontent.com/9021911/137440682-9d8fcc1a-6711-468a-bf89-15146d23263b.jpg)

But the gap becomes smaller if I change to the fractional size:

```
  <Shadow
    distance={15}
    startColor={'#000000ff'}
    finalColor={'#00000000'}
    offset={[10, 0]}
    radius={10}
    size={[101.93, 101.93]}
  >
    <View
      style={[
        {
          width: 101.93,
          height: 101.93,
          borderRadius: 10,
          backgroundColor: '#fff',
        },
      ]}
    ></View>
  </Shadow>
```
![37603efa9847fc83680f61a844a65b7](https://user-images.githubusercontent.com/9021911/137440897-cd43d281-1485-4a18-9e13-27f190e8be21.jpg)

**Comment by SrBrahma** [comment]
You are being very helpful! Thanks a lot, really.

Three questions:

a) Are you using the copied .tsx file or changing the .js in node_modules? I ask this because sometimes when changing the node_modules files they won't take effect right away.

b) Just to be sure, are you using react-native-svg@12.1.1, right?

c) Are you using RTL? If you don't know what this is, you are not using and that's ok (would also be ok to use it)


Using the previous component:

```tsx
 <Shadow
    distance={15}
    startColor={'#00f9'}
    finalColor={'#f009'}
    radius={0}
    size={[100, 100]}
    paintInside
  />
```

No need to send images for the requests below as I don't want to give you too much work, but be very attentive with the answers. For each item, watch out for any changes and report them or say that there are visible no changes.

For right gap:

1) Add `, backgroundColor: '#000', width: 100, height: 100` in paintInside svg style, at line 410. See if the gap between the center square and the right shadow is filled with black. If the black grows by more pixels than it should, change the `widthWithAdditional` and `heightWithAdditional` to `100` at the line above, 409. At least, there **must** be a visible black square below/above the center square. If not, the changes aren't taking effect.

2) If above doesn't work, undo the changes and do the same for the right shadow style, with `, backgroundColor: '#000', width: 15, height: 100`.  You may also need to change the WithAdditional to 15 and 100, like above.

3) Undo everything and add `viewBox={'0 0 15 100'}` prop to line 329 and `viewBox={'0 0 100 100'}` to now line 412. This shouldn't work if any of the two above didn't work, but not bad trying anyway. If above worked, this may fill the gap properly.

4) If no success, undo and at line 328 change `left: -distance` to `right: 0`.

Undo everything above. For top overlap:

1) Add `viewBox={'0 0 100 15'}` to line 345.

2) If no success, undo and add `width: 100, height: 15` to styles at line 344. Look for changes and then change the corresponding WithAdditional props at the line above with the same values.

3) If no success, undo and change `top: -distance` at 344 to `transform: [{translateY: -distance}]`

4) If no success, undo and change `top: -distance` at 344 to `bottom: 115`. Maybe the overlap will turn into a gap.

If we don't achieve success and I don't have any more ideas, I will open an Issue at the react-native-svg repo requesting for help.

Once again, thank you very much for your service! :)

**Comment by walterholohan** [comment]
I am getting the same issue when I apply an offset to my shadow. A 1 pixel gap appears on iOS (Android is fine)

```
<Shadow
				distance={SPACING.s12}
				viewStyle={{ alignSelf: 'stretch' }}
				radius={SPACING.s16}
				startColor={COLORS.primary}
				finalColor={SHADOW_COLORS.finalColor}
				offset={[0, 2]}
				safeRender
			>
```
<img width="437" alt="image" src="https://user-images.githubusercontent.com/5293650/152980360-fbe9e77f-936a-40d1-a952-cf3a040cd2e9.png">

**Comment by SrBrahma** [comment]
Thanks, @walterholohan . Just on the bottom side?

I have an iOS now and when I have the time I will investigate this.

**Comment by walterholohan** [comment]
Nope its on the right side too if I add a x offset
