### ISSUE TITLE
Support for Animated?

### ISSUE THREAD

**Issue by Decezaris** [SrBrahma/react-native-shadow-2#51]
The lib has support to add shadow with Animated View?

I have a progress bar, and I'd like to put a collored shadow to emulate a neon behavior.

![image](https://user-images.githubusercontent.com/23064759/168680568-e8c37057-4eb3-4b91-98b7-9624a6fab8b4.png)

**Comment by SrBrahma** [comment]
Hi, I don't know if it's possible for SVG. I found a lib [react-native-svg-animations](https://github.com/73R3WY/react-native-svg-animations), but it seems it only supports SVG's Path component, not Rect etc that we also use. We can't use Path at some parts as we use '%' sizes for the first render.

What you may try is have your bar as an Animated.View and wrap it with the Shadow. Ain't certain if it would work, but maybe it does, although with a delay. You may try also to comment those two lines in the package .js files:

https://github.com/SrBrahma/react-native-shadow-2/blob/ce32eea4a17580447a0e75444881aed23c9b9e8a/src/index.tsx#L487-L488

Commenting them, the Shadow would use '100%' width and height instead of pixel perfect that was acquired via onLayout. In theory this would make the Shadow have the same size of your animated Children in the same render, although eventually it may happen some very tiny artifacts between sides and corners (that certainly wouldn't be visible in your case) as % sizing and positioning isn't exact. You should try this, anyway.

What maybe could also work is if you have a width state that increased over the time. If I am not mistaken Animated or Reanimated have something like this to be used without having an Animated component. (maybe [this](https://github.com/react-native-svg/react-native-svg/issues/121#issuecomment-244142220)?)

I don't have yet much experience with animations, so I don't think I can help further than that.

**Comment by SrBrahma** [comment]
Please try the given alternatives and give me your feedback. Depending on how they go, I can improve the support for Animations.

**Comment by Decezaris** [comment]
Sure, I'm busy now with other stuff, but I will try asap, and I will put the results here.

**Comment by SrBrahma** [comment]
In your time!

**Comment by SrBrahma** [comment]
Closed due to inactivity
