### ISSUE TITLE
Issue with borderRadius in the latest version 7 when size of the elements changes

### ISSUE THREAD

**Issue by midrizi** [SrBrahma/react-native-shadow-2#72]
With version 7:
https://snack.expo.dev/pawromLkg

![image](https://user-images.githubusercontent.com/56638730/236641407-e2f04b2b-a697-469b-8a00-a2bfb127abf5.png)

With version 6:
https://snack.expo.dev/m1WNh4Ekc

![image](https://user-images.githubusercontent.com/56638730/236641477-59aa9916-4a87-47ed-9512-7f6198874f5c.png)

**Comment by SrBrahma** [comment]
Thanks for the report. It seems that the code that takes care of the radii limitation is not considering when the child changes its size. I will take a look when I have the time. In the meantime, you may want to try a smaller radius, which wouldn't be limited by the small child size.

**Comment by SrBrahma** [comment]
Beware that in v7 we no longer use the radius property, but the `style={{ borderRadius: 10 }}`, so that's what you want to change.

Here it worked, although there is a visual artifact that also needs to be fixed.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/28177550/236642011-5bc6d8a4-6296-41f1-8dfb-e485a1291bcd.png">

Setting the borderRadius to 8 gives a clean result on Web. Not a good solution, but a workaround in the meantime.

**Comment by SrBrahma** [comment]
As this is an ugly bug, I will try to fix it on Monday. Thanks once again for the report!

**Comment by SrBrahma** [comment]
Hi, sorry for the delay. I was trying to fix that artifact on the web (
<img width="30" alt="image" src="https://github.com/SrBrahma/react-native-shadow-2/assets/28177550/3e3c14a5-ae6a-418c-a61f-6f10ad871a86">
)
but it seems to be a non-deterministic issue caused by high-resolution screens that have window.devicePixelRatio !== 1. Mine for example, in my quite new laptop, is 1.5. It was taking too long (and nothing I tried worked), so I decided to just update the package with the original issue fix, under 7.0.8. Please, let me know if it fixed your problem.
