### ISSUE TITLE
the shadow can not  as same as web css

### ISSUE THREAD

**Issue by JRfan123** [SrBrahma/react-native-shadow-2#81]
```
 <Shadow
          startColor="rgba(42, 96, 255, 0.25)"
          distance={4}
          offset={[0, 4]}
          style={{ borderRadius: 24, height: 48, width: '100%' }}
        >
          <Text
            style={{
              textAlign: 'center',
              fontWeight: '500',
              fontSize: 18,
              color: 'rgba(255, 255, 255, 1)',
            }}
          >
            111
          </Text>
        </Shadow>

```
<img width="344" alt="image" src="https://github.com/SrBrahma/react-native-shadow-2/assets/158460447/7cc698e9-5976-488f-a97c-0975ada79c35">

 css:   box-shadow: 0px 10px 20px -10px rgba(42, 96, 255, 0.25), 0px 10px 20px -10px rgba(14, 26, 236, 0.70);
<img width="370" alt="image" src="https://github.com/SrBrahma/react-native-shadow-2/assets/158460447/8a7c4d7d-6fc4-4a32-b8ed-d7060ccf078a">

**Comment by SrBrahma** [comment]
Hi, @JRfan123!

Due to how this library works (we create an SVG image), there is no direct conversion to CSS shadow, as there are many limitations to what we can do with SVG.

If you are doing a mobile & web app and want a fine-tuning of the Shadow for web, what you can do is if the `Platform` is web, you can use the `disabled` property to the Shadow component and pass the CSS shadow style to your component. You can create a wrapping Shadow component to imply this logic.

Let me know if you have further questions ;)

**Comment by JRfan123** [comment]
ok， thank you
